"""keep_only_shipping_records_navigation

Revision ID: 449ca36e7a64
Revises: '54da069a149e'
Create Date: generated by alembic

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op


revision: str = "449ca36e7a64"
down_revision: Union[str, Sequence[str], None] = '54da069a149e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Keep only WMS-side shipping records navigation under Shipping Assist.

    Logistics has become the independent owner of quote, pricing, provider,
    waybill, shipment execution, billing and reconciliation operations.
    WMS keeps only shipping_records as the local ledger/read model used by
    records, finance and reports.
    """

    op.execute(
        """
        UPDATE page_registry
           SET is_active = CASE
                 WHEN code IN (
                   'shipping_assist',
                   'shipping_assist.shipping',
                   'shipping_assist.shipping.records'
                 )
                 THEN TRUE
                 ELSE FALSE
               END
         WHERE code = 'shipping_assist'
            OR code LIKE 'shipping_assist.%'
        """
    )

    op.execute(
        """
        UPDATE page_route_prefixes
           SET is_active = CASE
                 WHEN route_prefix = '/shipping-assist/shipping/records'
                 THEN TRUE
                 ELSE FALSE
               END
         WHERE route_prefix LIKE '/shipping-assist/%'
        """
    )


def downgrade() -> None:
    """Restore the pre-split WMS Shipping Assist navigation entries.

    Do not restore already-retired quote/settings routes.
    """

    op.execute(
        """
        UPDATE page_registry
           SET is_active = TRUE
         WHERE code IN (
           'shipping_assist',
           'shipping_assist.shipping',
           'shipping_assist.shipping.records',
           'shipping_assist.pricing',
           'shipping_assist.pricing.providers',
           'shipping_assist.pricing.bindings',
           'shipping_assist.pricing.templates',
           'shipping_assist.billing',
           'shipping_assist.billing.items',
           'shipping_assist.billing.reconciliation'
         )
        """
    )

    op.execute(
        """
        UPDATE page_route_prefixes
           SET is_active = TRUE
         WHERE route_prefix IN (
           '/shipping-assist/shipping/records',
           '/shipping-assist/pricing/providers',
           '/shipping-assist/pricing/bindings',
           '/shipping-assist/pricing/templates',
           '/shipping-assist/billing/items',
           '/shipping-assist/billing/reconciliation'
         )
        """
    )
