"""add_logistics_shipping_record_sync_cursor

Revision ID: 54da069a149e
Revises: '8f814d7762dc'
Create Date: generated by alembic

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "54da069a149e"
down_revision: Union[str, Sequence[str], None] = '8f814d7762dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "logistics_shipping_record_sync_cursors",
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("last_cursor", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.PrimaryKeyConstraint(
            "source",
            name="logistics_shipping_record_sync_cursors_pkey",
        ),
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS logistics_shipping_record_sync_cursors")
