"""register shipping assist handoffs page

Revision ID: 7abe99f04b00
Revises: 'ec6037fb0e66'
Create Date: generated by alembic

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op


revision: str = '7abe99f04b00'
down_revision: Union[str, Sequence[str], None] = 'ec6037fb0e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Register Shipping Assist handoffs page.

    发货辅助当前保留两类 WMS 本地页面：
    - 发货交接：wms_logistics_export_records，观察 WMS -> Logistics 交接状态；
    - 发货记录：shipping_records，观察 Logistics 完成后回写的包裹级发货事实。
    """

    op.execute(
        """
        INSERT INTO page_registry (
          code,
          name,
          read_permission_id,
          write_permission_id,
          sort_order,
          is_active,
          parent_code,
          level,
          domain_code,
          show_in_topbar,
          show_in_sidebar,
          inherit_permissions
        )
        VALUES (
          'shipping_assist.handoffs',
          '发货交接',
          NULL,
          NULL,
          10,
          TRUE,
          'shipping_assist',
          2,
          'shipping_assist',
          FALSE,
          TRUE,
          TRUE
        )
        ON CONFLICT (code) DO UPDATE SET
          name = EXCLUDED.name,
          read_permission_id = EXCLUDED.read_permission_id,
          write_permission_id = EXCLUDED.write_permission_id,
          sort_order = EXCLUDED.sort_order,
          is_active = TRUE,
          parent_code = EXCLUDED.parent_code,
          level = EXCLUDED.level,
          domain_code = EXCLUDED.domain_code,
          show_in_topbar = EXCLUDED.show_in_topbar,
          show_in_sidebar = EXCLUDED.show_in_sidebar,
          inherit_permissions = EXCLUDED.inherit_permissions
        """
    )

    op.execute(
        """
        UPDATE page_registry
           SET is_active = TRUE,
               parent_code = 'shipping_assist',
               level = 2,
               domain_code = 'shipping_assist',
               show_in_topbar = FALSE,
               show_in_sidebar = TRUE,
               inherit_permissions = TRUE,
               read_permission_id = NULL,
               write_permission_id = NULL,
               sort_order = 20
         WHERE code = 'shipping_assist.records'
        """
    )

    op.execute(
        """
        UPDATE page_registry
           SET is_active = CASE
                 WHEN code IN (
                   'shipping_assist',
                   'shipping_assist.handoffs',
                   'shipping_assist.records'
                 )
                 THEN TRUE
                 ELSE FALSE
               END
         WHERE code = 'shipping_assist'
            OR code LIKE 'shipping_assist.%'
        """
    )

    op.execute(
        """
        INSERT INTO page_route_prefixes (
          page_code,
          route_prefix,
          sort_order,
          is_active
        )
        VALUES (
          'shipping_assist.handoffs',
          '/shipping-assist/handoffs',
          10,
          TRUE
        )
        ON CONFLICT (route_prefix) DO UPDATE SET
          page_code = EXCLUDED.page_code,
          sort_order = EXCLUDED.sort_order,
          is_active = TRUE
        """
    )

    op.execute(
        """
        UPDATE page_route_prefixes
           SET sort_order = 20,
               is_active = TRUE,
               page_code = 'shipping_assist.records'
         WHERE route_prefix = '/shipping-assist/records'
        """
    )

    op.execute(
        """
        UPDATE page_route_prefixes
           SET is_active = CASE
                 WHEN route_prefix IN (
                   '/shipping-assist/handoffs',
                   '/shipping-assist/records'
                 )
                 THEN TRUE
                 ELSE FALSE
               END
         WHERE route_prefix LIKE '/shipping-assist/%'
            OR page_code = 'shipping_assist'
            OR page_code LIKE 'shipping_assist.%'
        """
    )


def downgrade() -> None:
    """Restore Shipping Assist records-only navigation."""

    op.execute(
        """
        DELETE FROM page_route_prefixes
         WHERE route_prefix = '/shipping-assist/handoffs'
        """
    )

    op.execute(
        """
        DELETE FROM page_registry
         WHERE code = 'shipping_assist.handoffs'
        """
    )

    op.execute(
        """
        UPDATE page_registry
           SET sort_order = 10,
               is_active = TRUE,
               parent_code = 'shipping_assist',
               level = 2,
               domain_code = 'shipping_assist',
               show_in_topbar = FALSE,
               show_in_sidebar = TRUE,
               inherit_permissions = TRUE,
               read_permission_id = NULL,
               write_permission_id = NULL
         WHERE code = 'shipping_assist.records'
        """
    )

    op.execute(
        """
        UPDATE page_registry
           SET is_active = CASE
                 WHEN code IN (
                   'shipping_assist',
                   'shipping_assist.records'
                 )
                 THEN TRUE
                 ELSE FALSE
               END
         WHERE code = 'shipping_assist'
            OR code LIKE 'shipping_assist.%'
        """
    )

    op.execute(
        """
        UPDATE page_route_prefixes
           SET sort_order = 10,
               is_active = CASE
                 WHEN route_prefix = '/shipping-assist/records'
                 THEN TRUE
                 ELSE FALSE
               END
         WHERE route_prefix LIKE '/shipping-assist/%'
            OR page_code = 'shipping_assist'
            OR page_code LIKE 'shipping_assist.%'
        """
    )
