"""align_shipping_records_package_comment

Revision ID: 8f814d7762dc
Revises: 'b9c24ee10cba'
Create Date: generated by alembic

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f814d7762dc"
down_revision: Union[str, Sequence[str], None] = 'b9c24ee10cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_NEW_COMMENT = "包裹序号，从 1 开始；物流台账内部包裹序号"
_OLD_COMMENT = "包裹序号，从 1 开始，对应 order_shipment_prepare_packages.package_no"


def upgrade() -> None:
    op.alter_column(
        "shipping_records",
        "package_no",
        existing_type=sa.Integer(),
        existing_nullable=False,
        comment=_NEW_COMMENT,
    )


def downgrade() -> None:
    op.alter_column(
        "shipping_records",
        "package_no",
        existing_type=sa.Integer(),
        existing_nullable=False,
        comment=_OLD_COMMENT,
    )
