"""retire_wms_shipping_assist_dead_navigation

Revision ID: 98109692b929
Revises: '3fc161fb9104'
Create Date: generated by alembic

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "98109692b929"
down_revision: Union[str, Sequence[str], None] = '3fc161fb9104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Retire WMS navigation entries whose public runtime routes moved to logistics-api."""

    op.execute(
        """
        DELETE FROM page_route_prefixes
        WHERE route_prefix IN (
          '/shipping-assist/shipping/quote',
          '/shipping-assist/settings/waybill'
        )
           OR page_code IN (
          'shipping_assist.shipping.quote',
          'shipping_assist.settings.waybill',
          'shipping_assist.settings'
        )
        """
    )

    op.execute(
        """
        DELETE FROM page_registry
        WHERE code IN (
          'shipping_assist.shipping.quote',
          'shipping_assist.settings.waybill'
        )
        """
    )

    op.execute(
        """
        DELETE FROM page_registry
        WHERE code = 'shipping_assist.settings'
        """
    )


def downgrade() -> None:
    """Restore retired WMS navigation entries."""

    op.execute(
        """
        INSERT INTO page_registry (
          code,
          name,
          parent_code,
          level,
          domain_code,
          show_in_topbar,
          show_in_sidebar,
          inherit_permissions,
          read_permission_id,
          write_permission_id,
          sort_order,
          is_active
        )
        VALUES
          (
            'shipping_assist.settings',
            '设置',
            'shipping_assist',
            2,
            'shipping_assist',
            FALSE,
            TRUE,
            TRUE,
            NULL,
            NULL,
            40,
            TRUE
          ),
          (
            'shipping_assist.shipping.quote',
            '发货算价',
            'shipping_assist.shipping',
            3,
            'shipping_assist',
            FALSE,
            TRUE,
            TRUE,
            NULL,
            NULL,
            10,
            TRUE
          ),
          (
            'shipping_assist.settings.waybill',
            '电子面单配置',
            'shipping_assist.settings',
            3,
            'shipping_assist',
            FALSE,
            TRUE,
            TRUE,
            NULL,
            NULL,
            10,
            TRUE
          )
        ON CONFLICT (code) DO UPDATE
        SET
          name = EXCLUDED.name,
          parent_code = EXCLUDED.parent_code,
          level = EXCLUDED.level,
          domain_code = EXCLUDED.domain_code,
          show_in_topbar = EXCLUDED.show_in_topbar,
          show_in_sidebar = EXCLUDED.show_in_sidebar,
          inherit_permissions = EXCLUDED.inherit_permissions,
          read_permission_id = EXCLUDED.read_permission_id,
          write_permission_id = EXCLUDED.write_permission_id,
          sort_order = EXCLUDED.sort_order,
          is_active = EXCLUDED.is_active
        """
    )

    op.execute(
        """
        INSERT INTO page_route_prefixes (
          route_prefix,
          page_code,
          sort_order,
          is_active
        )
        VALUES
          (
            '/shipping-assist/shipping/quote',
            'shipping_assist.shipping.quote',
            10,
            TRUE
          ),
          (
            '/shipping-assist/settings/waybill',
            'shipping_assist.settings.waybill',
            80,
            TRUE
          )
        ON CONFLICT (route_prefix) DO UPDATE
        SET
          page_code = EXCLUDED.page_code,
          sort_order = EXCLUDED.sort_order,
          is_active = EXCLUDED.is_active
        """
    )
