"""drop_wms_logistics_migrated_tables

Revision ID: b9c24ee10cba
Revises: '98109692b929'
Create Date: generated by alembic

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b9c24ee10cba"
down_revision: Union[str, Sequence[str], None] = '98109692b929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Drop WMS-owned remnants whose runtime ownership moved to logistics-api.

    Keep shipping_records: it remains the WMS-side logistics ledger used by
    records, billing, reports, and finance.
    """

    op.execute("DROP TABLE IF EXISTS order_shipment_prepare_packages")
    op.execute("DROP TABLE IF EXISTS order_shipment_prepare")
    op.execute("DROP TABLE IF EXISTS transport_shipments")
    op.execute("DROP TABLE IF EXISTS electronic_waybill_configs")


def downgrade() -> None:
    """Data-destructive table retirement is intentionally not reversible."""

    raise RuntimeError(
        "Downgrade not supported: WMS logistics runtime tables were retired "
        "after ownership moved to logistics-api."
    )
