"""flatten_shipping_assist_records_navigation

Revision ID: ba082296a69d
Revises: '449ca36e7a64'
Create Date: generated by alembic

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op


revision: str = "ba082296a69d"
down_revision: Union[str, Sequence[str], None] = '449ca36e7a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Flatten WMS Shipping Assist navigation from 3 levels to 2 levels."""

    op.execute(
        """
        INSERT INTO page_registry (
            code,
            name,
            read_permission_id,
            write_permission_id,
            sort_order,
            is_active,
            parent_code,
            level,
            domain_code,
            show_in_topbar,
            show_in_sidebar,
            inherit_permissions
        )
        SELECT
            'shipping_assist.records',
            '发货记录',
            read_permission_id,
            write_permission_id,
            10,
            TRUE,
            'shipping_assist',
            2,
            domain_code,
            show_in_topbar,
            show_in_sidebar,
            inherit_permissions
          FROM page_registry
         WHERE code = 'shipping_assist.shipping.records'
        ON CONFLICT (code) DO UPDATE SET
            name = EXCLUDED.name,
            read_permission_id = EXCLUDED.read_permission_id,
            write_permission_id = EXCLUDED.write_permission_id,
            sort_order = EXCLUDED.sort_order,
            is_active = TRUE,
            parent_code = EXCLUDED.parent_code,
            level = EXCLUDED.level,
            domain_code = EXCLUDED.domain_code,
            show_in_topbar = EXCLUDED.show_in_topbar,
            show_in_sidebar = EXCLUDED.show_in_sidebar,
            inherit_permissions = EXCLUDED.inherit_permissions
        """
    )

    op.execute(
        """
        UPDATE page_registry
           SET is_active = CASE
                 WHEN code IN (
                   'shipping_assist',
                   'shipping_assist.records'
                 )
                 THEN TRUE
                 ELSE FALSE
               END
         WHERE code = 'shipping_assist'
            OR code LIKE 'shipping_assist.%'
        """
    )

    op.execute(
        """
        INSERT INTO page_route_prefixes (
            page_code,
            route_prefix,
            sort_order,
            is_active
        )
        VALUES (
            'shipping_assist.records',
            '/shipping-assist/records',
            10,
            TRUE
        )
        ON CONFLICT (route_prefix) DO UPDATE SET
            page_code = EXCLUDED.page_code,
            sort_order = EXCLUDED.sort_order,
            is_active = TRUE
        """
    )

    op.execute(
        """
        UPDATE page_route_prefixes
           SET is_active = CASE
                 WHEN route_prefix = '/shipping-assist/records'
                 THEN TRUE
                 ELSE FALSE
               END
         WHERE route_prefix LIKE '/shipping-assist/%'
        """
    )


def downgrade() -> None:
    """Restore the records-only 3-level WMS Shipping Assist navigation."""

    op.execute(
        """
        UPDATE page_registry
           SET is_active = CASE
                 WHEN code IN (
                   'shipping_assist',
                   'shipping_assist.shipping',
                   'shipping_assist.shipping.records'
                 )
                 THEN TRUE
                 WHEN code = 'shipping_assist.records'
                 THEN FALSE
                 ELSE is_active
               END
         WHERE code = 'shipping_assist'
            OR code LIKE 'shipping_assist.%'
        """
    )

    op.execute(
        """
        UPDATE page_route_prefixes
           SET is_active = CASE
                 WHEN route_prefix = '/shipping-assist/shipping/records'
                 THEN TRUE
                 WHEN route_prefix = '/shipping-assist/records'
                 THEN FALSE
                 ELSE is_active
               END
         WHERE route_prefix LIKE '/shipping-assist/%'
        """
    )
