"""drop_migrated_shipping_assist_tables

Revision ID: f24a651ec4a9
Revises: 'ba082296a69d'
Create Date: generated by alembic

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op


revision: str = "f24a651ec4a9"
down_revision: Union[str, Sequence[str], None] = 'ba082296a69d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


DROP_TABLES_IN_ORDER = (
    "shipping_bill_reconciliation_histories",
    "shipping_record_reconciliations",
    "carrier_bill_items",
    "warehouse_shipping_providers",
    "shipping_provider_contacts",
    "shipping_provider_pricing_template_validation_records",
    "shipping_provider_pricing_template_surcharge_config_cities",
    "shipping_provider_pricing_template_surcharge_configs",
    "shipping_provider_pricing_template_matrix",
    "shipping_provider_pricing_template_destination_group_members",
    "shipping_provider_pricing_template_destination_groups",
    "shipping_provider_pricing_template_module_ranges",
    "shipping_provider_pricing_templates",
)


def upgrade() -> None:
    """Drop WMS-side Shipping Assist tables whose data has moved to Logistics."""

    for table_name in DROP_TABLES_IN_ORDER:
        op.drop_table(table_name)


def downgrade() -> None:
    """No-op downgrade.

    These tables were migrated to the standalone Logistics database before being
    removed from WMS. Restoring their data requires replaying the Logistics import
    source or restoring from backup, not a schema-only downgrade.
    """
    pass
